### ISSUE TITLE
'yesno_option' in the models/bert/run_quac_train.py

### ISSUE THREAD

**Issue by cipolee** [princeton-nlp/EvalConvQA#4]
hi, i found '**yesno_option**' is used in run_quac_dataset_utils.py and run_quac_train.py, however, it isn't initialized in Example and the forward function of bertmodel does not have this variable. 
Although I resolved this bug through hack processing, it is also possible that I made another error. Can you explain the purpose of setting this variable？ Thank you！

**Comment by gaotianyu1350** [comment]
@huihanlhh Can you take a look?

**Comment by 1605wzf** [comment]
I have the same problems.Can you tell me how to slove this? Thank you !

**Comment by 1605wzf** [comment]
> hi, i found '**yesno_option**' is used in run_quac_dataset_utils.py and run_quac_train.py, however, it isn't initialized in Example and the forward function of bertmodel does not have this variable.嗨，我发现run_quac_dataset_utils.py和run_quac_train.py中使用了“yesno_option”，但是，它没有在示例中初始化，并且 bertmodel 的前向函数没有此变量。 Although I resolved this bug through hack processing, it is also possible that I made another error. Can you explain the purpose of setting this variable？ Thank you！虽然我通过黑客处理解决了这个错误，但也有可能我犯了另一个错误。你能解释一下设置这个变量的目的吗？谢谢！

**Comment by 1605wzf** [comment]
> hi, i found '**yesno_option**' is used in run_quac_dataset_utils.py and run_quac_train.py, however, it isn't initialized in Example and the forward function of bertmodel does not have this variable. Although I resolved this bug through hack processing, it is also possible that I made another error. Can you explain the purpose of setting this variable？ Thank you！

I have the same problems. Can you tell me how to slove this problem? Thank you!
