### ISSUE TITLE
Download link for HAM checkpoint

### ISSUE THREAD

**Issue by cipolee** [princeton-nlp/EvalConvQA#5]
hi
The HAM checkpoint's URL you provide links to vocab.txt instead of the model file. Can you check this issue and provide a new checkpoint URL link?
Thanks!

**Comment by huihanlhh** [comment]
Hi! The link we provided was the official link on the github repo of the HAM paper: https://github.com/prdwb/attentive_history_selection
I can see that currently the link to their CodaLab checkpoint is invalid too. In that case, I suggest you directly contact the HAM author and ask for an updated link of their model.

**Comment by cipolee** [comment]
Thanks
